-- Database: ONLINE_PHARMACY

-- DROP DATABASE "ONLINE_PHARMACY";

CREATE DATABASE "ONLINE_PHARMACY"
    WITH 
    OWNER = user_piu
    ENCODING = 'UTF8'
    LC_COLLATE = 'C'
    LC_CTYPE = 'C'
    TABLESPACE = pg_default
    CONNECTION LIMIT = -1;

COMMENT ON DATABASE "ONLINE_PHARMACY"
    IS 'ONLINE_PHARMACY DATABASE';